image: maven:3.6-jdk-13

compile:
  stage: build
  only: 
    - master
    - rest
  script:
    - mvn compile --batch-mode
 
verify:
  only: 
    - master
    - rest
  script:
    - mvn verify --batch-mode
    - mvn package --batch-mode
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
        - ./target/*.jar
