image: maven:3.6-jdk-13
 
compile:
  stage: build
  only: 
    - master
  script:
    - mvn compile --batch-mode
    - mvn package --batch-mode
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
        - ./target/*.jar
 
verify:
  only: 
    - master
  script:
    - mvn verify --batch-mode
