image: maven:3.5.0-jdk-8
 
compile:
  stage: build
  script:
    - mvn compile --batch-mode
    - mvn package --batch-mode
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
        - ./target/*.jar
 
verify:
  script:
    - mvn verify --batch-mode
